### PR TITLE
[DBZ-1406] Replace Yaml Dependency With Property file.

### PR DESCRIPTION
**Pull request by bingqinzhou**
Use Property file instead of Yaml file for Cassandra Connector Config to get rid of SnakeYaml dependency.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, thanks a lot, @bingqinzhou! I reckon that an update to @jgao54's in-flight doc PR in the debezium.github.io repo is needed, too? Could you push a commit to that PR for this? And could you author the commit using an e-mail that's assigned to your GitHub account? That way your contributions will [show up properly](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile) in the project stats. Thanks!

**Comment by bingqinzhou** [comment]
> LGTM, thanks a lot, @bingqinzhou! I reckon that an update to @jgao54's in-flight doc PR in the debezium.github.io repo is needed, too? Could you push a commit to that PR for this? And could you author the commit using an e-mail that's assigned to your GitHub account? That way your contributions will [show up properly](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile) in the project stats. Thanks!

Thanks @gunnarmorling for your comments! 
- I updated this PR a bit since I failed to realize that all configs read from .properties file are String type. 
- I feel I'm already authoring the commits using my Github account email (bing.zhou@husky.neu.edu) since I can observe my contribution activities on my Github profile..
- I'm not sure if I have access to update Joy's doc PR.. I guess maybe I should wait until the doc PR gets merged then create another one base on it..?

**Comment by gunnarmorling** [comment]
> I feel I'm already authoring the commits using my Github account email 

@bingqinzhou, looking into the commits of this PR, they are authored using your WePay address; so you could either add that one to your GH account, or you could rework the commits to use the other one.

> I'm not sure if I have access to update Joy's doc PR

I'll merge that one later today, so you could create a new PR with your changes off of upstream/develop then.

**Comment by bingqinzhou** [comment]
> > I feel I'm already authoring the commits using my Github account email
> 
> @bingqinzhou, looking into the commits of this PR, they are authored using your WePay address; so you could either add that one to your GH account, or you could rework the commits to use the other one.
> 
> > I'm not sure if I have access to update Joy's doc PR
> 
> I'll merge that one later today, so you could create a new PR with your changes off of upstream/develop then.

@gunnarmorling Got it! I've added my WePay email to my Github account, please let know if it looks good to you now, otherwise I can re-write this commit with my primary Github account :) I also have a PR to update the cassandra connector doc:https://github.com/debezium/debezium.github.io/pull/345

**Pull request merged**
