### PR TITLE
[DBZ-2103] Ultimate fix for data mismatch error.

### PR DESCRIPTION
**Pull request by bingqinzhou**
Final fix for issue described in https://issues.redhat.com/browse/DBZ-2103 by making all column type optional consistently.

### CODE REVIEW

**Comment by bingqinzhou** [comment]
@gunnarmorling May I get a review for PR? Please let me know if you have any concern about this change. Thank you!

**Comment by gunnarmorling** [comment]
@bingqinzhou, so are those values always optional actually? I.e. there's no way to declare them as _NOT NULL_ as in SQL?

**Comment by bingqinzhou** [comment]
> @bingqinzhou, so are those values always optional actually? I.e. there's no way to declare them as _NOT NULL_ as in SQL?

@gunnarmorling I don't think we should force any value schema to be non-opitional:
- There doesn't seem to be a `NOT NULL` constraint for Cassandra columns.
- Even if the value of a column is not supposed to be `null`, if the column is `deleted` or not included in an `update` operation of the row, the deserialized value of this column (from it's corresponding mutation in commitLog) should still be `null` in kafka message.

**Comment by gunnarmorling** [comment]
Ok, that makes sense. Thanks! Will merge.

**Pull request merged**
