### PR TITLE
[DBZ-2512]: Fix error for UUID collection type

### PR DESCRIPTION
**Pull request by bingqinzhou**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@bingqinzhou, could you rebase this to master and squash into a single commit? Having a bit of a hard time to figure out what's actually changing. Thanks!

**Comment by bingqinzhou** [comment]
> @bingqinzhou, could you rebase this to master and squash into a single commit? Having a bit of a hard time to figure out what's actually changing. Thanks!

The commit history of my local master is somehow messed up and 462a5f4, 869b513, 8efe8bc are from closed PR #190. I'll create a new PR with cleaner commit history to replicate this one after #193 gets merged.

**Comment by gunnarmorling** [comment]
Ok, thanks. #193 is in now. We'll cut 1.3.0.Beta2 today, but we can include this one here in next week's CR1, so there won't be much of a delay caused by that.

**Comment by gunnarmorling** [comment]
I'm already going to close this one, so to clean the slate a bit. Thanks for creating a new one!

**Pull request closed without merging**
