### PR TITLE
WIP: DBZ-137 Using LogMiner API to stream data from Oracle

### PR DESCRIPTION
**Pull request by jchipmunk**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @jchipmunk, thanks! Are you working with @AndreyIg? He has filed a PR before around the LogMiner approach (https://github.com/debezium/debezium-incubator/pull/87) and continues to work on this; is this PR incorporating his changes? I'm a bit confused :)

**Comment by jchipmunk** [comment]
Hi @gunnarmorling, sorry, I didn't see #87 PR. My PR is independent of #87, but I implemented logic of working with LogMiner that can be used.

**Comment by gunnarmorling** [comment]
Hey @jchipmunk, so given the usage of CONTINUOUS_MINE (which is planned to be removed from Oracle), it seems to make most sense to proceed with the implementation of @AndreyIg et al.

I understand this may be a bit frustrating given the efforts you surely put it :( That being said, there's lots of things in this PR which could be used. So would you be ok if @AndreyIg grabbed those and added them to his work, co-authoring it with your GH user? Then this commit will be attributed to the two of you.

Thanks a lot!

**Comment by gunnarmorling** [comment]
Going to close this one, now that the work of @AndreyIg has been merged. Many thanks nevertheless, @jchipmunk, your efforts around Debezium are highly appreciated!

**Pull request closed without merging**
