### PR TITLE
[DBZ-2510] Add more logs.

### PR DESCRIPTION
**Pull request by bingqinzhou**
Replicate https://github.com/debezium/debezium-incubator/pull/191

### CODE REVIEW

**Comment by bingqinzhou** [comment]
Build failure is not related:
Screen Shot 2020-09-15 at 2 34 01 PM

**Review by jgao54 — APPROVED** [review]
Thanks @bingqinzhou! LGTM

**Comment by jgao54** [comment]
curious what errors you are seeing and how often does it occur? (apologize if there is a JIRA on this that I am completely oblivious of)

**Comment by gunnarmorling** [comment]
Applied, thx, @bingqinzhou!

@jgao54, good question. Not sure whether it was a measure of pre-caution or driven by actual issues? Bingqin should know more.

Re the build error, I'm going to look into it. The repo organization is a bit unfortunate atm. For 1.4, we'll move to a model where each of the incubating and/or community-led connectors like Cassandra is located in its own repo, so you'll be much less affected by changes relating only to other connectors.

**Comment by bingqinzhou** [comment]
> Applied, thx, @bingqinzhou!
> 
> @jgao54, good question. Not sure whether it was a measure of pre-caution or driven by actual issues? Bingqin should know more.
> 
> Re the build error, I'm going to look into it. The repo organization is a bit unfortunate atm. For 1.4, we'll move to a model where each of the incubating and/or community-led connectors like Cassandra is located in its own repo, so you'll be much less affected by changes relating only to other connectors.

Just want to log table, column and datatype whenever any errors are encountered so it's easier for us to debug, the issues in DBZ-2512 and DBZ-2498 drive this need initially :)

**Pull request merged**
