### PR TITLE
DBZ-1491 Changes required after core refactoring

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1491

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Do you know what's wrong with the build, @Naros?

**Comment by Naros** [comment]
I'm looking into it now, but I honestly don't yet have a clue @gunnarmorling.

**Comment by Naros** [comment]
So first thing I uncovered was a formatting issue with a recent Cassandra push; applied that in commit 36ff07d. 
Now testing build status.

**Comment by Naros** [comment]
@gunnarmorling The first build must have been some network glitch I assume, this should be good for merge now.

**Comment by gunnarmorling** [comment]
Applied, thx!

**Pull request merged**
