### PR TITLE
DBZ-1345 Add test to verify snapshot ignores materialized views

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1345

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, could you verify and merge this one? Thanks!

**Comment by jpechane** [comment]
@gunnarmorling Will do!

**Comment by jpechane** [comment]
Oracle supports streaming of mat view so it was decided to keep the support of mat views in the connector - https://gitter.im/debezium/dev?at=5d134209501ea60f12494ea3

**Comment by jpechane** [comment]
@Naros Thanks for the effort!

**Pull request closed without merging**
