### PR TITLE
Dbz 3057

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3057

I'm opening this as a Draft currently because there is still one action item that remains, backporting the changes for DBZ-2456 to the Oracle connector.  That's currently being developed.

### CODE REVIEW

**Comment by Naros** [comment]
After reviewing the changes needed for DBZ-2456, it made more sense to move that to another issue since its going to require some substantial rework and is technically an enhancement and not a bug.  Moving PR to awaiting review.

**Comment by gunnarmorling** [comment]
Can we add a test for the specific situtation of global temporary tables mentioned in the original issue?

**Comment by Naros** [comment]
Hi @gunnarmorling, there is a global temporary table used in the new test named:
`shouldReadTableUniqueIndicesWithCharactersThatRequireExplicitQuotes`

**Comment by gunnarmorling** [comment]
Ah, gotcha, was distracted by the index stuff. Thx, LGTM!

**Pull request merged**
