### PR TITLE
DBZ-137 implement DML parsing

### PR DESCRIPTION
**Pull request by AndreyIg**
This PR should be clean

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks, @AndreyIg! We'll get to this asap.

**Comment by nyiny123** [comment]
I'm adding some description as been requested.
inputs for DML parser tests were taken from the real LogMiner output, so I'm confident we are testing the right things.
I mimicked XStream interfaces and classes to make reusable parts of the connector for both : XStream and LogMiner.
I placed generated record class (RowLCR) into DML parser for now and did not tie DML with the emitter yet to avoid large code changes/review

**Comment by gunnarmorling** [comment]
Hey @nyiny123, thanks a lot for this! Just a quick heads-up; I'll review this in the course of next week. I had to prepare a lab for Red Hat Summit in two weeks, that's why I couldn't do it earlier.

**Comment by gunnarmorling** [comment]
Closing this one as it's superseded by #87. Thanks, @AndreyIg!

**Pull request closed without merging**
