### PR TITLE
DBZ-1752 DB2 connector follow-up tasks

### PR DESCRIPTION
**Pull request by lga-zurich**
This pull request addresses:
- Use only DB2 compatible isolation modes when taking Snapshots
- Remove some unused variables

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, thanks! Can you send a PR for updating the docs in regards to the locking option, too?

In terms of releases: we did 1.1 Beta1 yesterday (announcement still pending), so this will be in the next 1.1 preview release (Beta2 or CR2, still to be decided). These releases happen every three weeks give or take, and there should be a new minor (1.1, 1.2, etc.) every quarter.

**Comment by gunnarmorling** [comment]
Ah, one other thing: could you please always prefix commit messages with the issue key (DBZ-1752...) and avoid merge commits (i.e. prefer rebases, for the sake of cleaner history). It's fine to force-push to a PR branch for updating such things (in this case here I'd squash everything into one anyways, as e.g. the formatting commit doesn't add much value in the history in the long term). Thanks!

**Comment by lga-zurich** [comment]
> Ah, one other thing: could you please always prefix commit messages with the issue key (DBZ-1752...) and avoid merge commits (i.e. prefer rebases, for the sake of cleaner history). It's fine to force-push to a PR branch for updating such things (in this case here I'd squash everything into one anyways, as e.g. the formatting commit doesn't add much value in the history in the long term). Thanks!

Yes, I always forget, done!

**Comment by lga-zurich** [comment]
> LGTM, thanks! Can you send a PR for updating the docs in regards to the locking option, too?

There you go debezium/debezium#1246

**Comment by gunnarmorling** [comment]
Applied; thanks a lot, @lga-zurich!

**Pull request merged**
