### PR TITLE
Dbz 137 enrich oracle parser

### PR DESCRIPTION
**Pull request by nyiny123**
I just refactored the parser you have provided in a way MySQL is doing.
The parser extends common Antlr parser and implements a few DDLs, like create tables, alter table and delete table.
It does not cover full language definition yet.

### CODE REVIEW

**Comment by jpechane** [comment]
@nyiny123 Hi, thanks for the contribution! Generally it looks good to me. Could you please
* Keep the name of Oracle paraser and the parser test? It is probably unnecessary to rename them
* Rease the PR to the latest master and make sure it is compilable? There are two references to the parser class that are not now satisifed
* Squash the commits into a single one - esp. removing the merge commit
* Modify the commit message to `DBZ-137 commit message`

We need to be able to run the full testsuite on the code before further steps are taken.

**Comment by nyiny123** [comment]
Thanks, will do.Also I'm about to finalize the first phase of DML parser (INSERT, DELETE, UPDATE).Next week it will be ready.It also includes a few minor improvements of the DDL parser.Do you want it as a separate PR?

    On Friday, March 1, 2019, 6:26:10 AM PST, Jiri Pechanec <notifications@github.com> wrote:  
 
 
@nyiny123 Hi, thanks for the contribution! Generally it looks good to me. Could you please
   
   - Keep the name of Oracle paraser and the parser test? It is probably unnecessary to rename them
   - Rease the PR to the latest master and make sure it is compilable? There are two references to the parser class that are not now satisifed
   - Squash the commits into a single one - esp. removing the merge commit
   - Modify the commit message to DBZ-137 commit message

We need to be able to run the full testsuite on the code before further steps are taken.

**Comment by jpechane** [comment]
@nyiny123 Hi, if possible I'd prefer it as a separate PR. It would be better first to provide the same functionlaity with reworked parser and then built upon it.

**Comment by nyiny123** [comment]
Hi, Jiri.
I hope this is what you wanted, please review.
Thanks

**Comment by jpechane** [comment]
@nyiny123 Have you had a chance to run it with integration tests? `OracleConnectorFilterIT` is failing with parser error.

**Comment by nyiny123** [comment]
Hi, Jiri.
I don't have full integration test environment locally, because I relied on your CI/CD pipeline which shows both unit and integration tests green for this commit. The strange thing is why it shows green, while one of the tests fail? Sorry if I misunderstood something, I'm still learning how to contribute to the open source project. 
Thanks,
Andrey

**Comment by jpechane** [comment]
@nyiny123 Unfortunately is is a pitfall with Oracle - we do not have automated CI for it - due to licensing and resource constaraints :-(

**Comment by nyiny123** [comment]
Hi, got back (was sick). 
Installed CDB and PDB per the doc, configured all the users and privs (found one OracleConnectorFilterIT inconsistency: line "GRANT SELECT_CATALOG_ROLE to " + TestHelper.CONNECTOR_USER, should be added ) . Currently all Integration tests hang on my system, at xsOut.receiveLCRCallback(handler, XStreamOut.DEFAULT_MODE);
I should have missed something in XStream Outbound server config, troubleshooting...

**Comment by nyiny123** [comment]
I believe I fixed that parsing problem(";" at the end of a DDL is a mandatory).
I'm ready to submit DML after you approve this

**Comment by jpechane** [comment]
@nyiny123 @gunnarmorling I've rebased the PR to the latest master and added one more commit fixing the case sensitiveness of Oracle identifiers - https://github.com/debezium/debezium-incubator/pull/77

**Comment by gunnarmorling** [comment]
Closing, as it was superseded by the (already merged) PR #77. Thanks, @nyiny123!

**Pull request closed without merging**
