### PR TITLE
DBZ-2711 Supplemental logging is required for entire database rather than per monitored table

### PR DESCRIPTION
**Pull request by ant0nk**
I've tested snapshotting and replication with only SUPPLEMENTAL_LOG_DATA_MIN enabled - all works same as with SUPPLEMENTAL_LOG_DATA_ALL.

### CODE REVIEW

**Comment by Naros** [comment]
Hi @ant0nk, I'm not sure I understand this change.

The goal of DBZ-2711 was to avoid the user setting any database-wide specific supplemental logging configuration and that it would instead be configured on a per-table basis.  This implies that this single query that checks the database setup would be altered to check that a monitored table has supplemental logging instead.

I haven't tested this theory, but I suspect we could use `dba_log_groups` and issue a query where `table_name = <table>` and check that the `LOG_GROUP_TYPE` is `ALL COLUMN LOGGING`.  If it isn't, we'd throw an exception.

**Comment by ant0nk** [comment]
Hi @Naros , Oracle documentation states - "Minimal supplemental logging logs the minimal amount of information needed for LogMiner to identify, group, and merge the redo operations associated with DML changes." So as I see it databasewide SUPPLEMENTAL_LOG_DATA_MIN is a must for Logminer to work. I can test what would be if supplemental logging isn't enabled for replicated tables, but I guess we just will not get `before` state of the changed data in this case.

**Comment by Naros** [comment]
Hi @ant0nk, so is my understanding inaccurate that you cannot configure supplemental logging two ways?

Database-wide setup:
```
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
```

Specific tables only:
```
ALTER TABLE myschema.mytable ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS
```

**Comment by ant0nk** [comment]
@Naros , yes, I guess so. I tried to test it - I dropped database-wide supplemental logging, left only table-specific settings (DBA_LOG_GROUPS.LOG_GROUP_TYPE=ALL COLUMN LOGGING), modified the connector check query - `"SELECT 'KEY', 'YES' FROM %s"`, and after restart of Connect I got an error:
```[2021-01-05 18:00:43,893] ERROR Mining session stopped due to the {} (io.debezium.connector.oracle.logminer.LogMinerHelper)
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8132
ORA-01354: Supplemental log data must be added to run this command
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8132
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4727
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4394
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4748
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4988
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8092
ORA-06512: at line 1
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 562
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 5328
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 5381
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 7983
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8146
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8302
ORA-06512: at "SYS.DBMS_LOGMNR_D", line 61
ORA-06512: at line 1
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
        at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
        at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
        at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
        at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
        at io.debezium.connector.oracle.logminer.LogMinerHelper.executeCallableStatement(LogMinerHelper.java:571)
        at io.debezium.connector.oracle.logminer.LogMinerHelper.buildDataDictionary(LogMinerHelper.java:89)
        at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.initializeRedoLogsForMining(LogMinerStreamingChangeEventSource.java:279)
        at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:143)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:140)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: Error : 604, Position : 0, Sql = BEGIN DBMS_LOGMNR_D.BUILD (options => DBMS_LOGMNR_D.STORE_IN_REDO_LOGS); END;, OriginalSql = BEGIN DBMS_LOGMNR_D.BUILD (options => DBMS_LOGMNR_D.STORE_IN_REDO_LOGS); END;, Error Msg = ORA-00604: error occurred at recursive SQL level 1
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8132
ORA-01354: Supplemental log data must be added to run this command
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8132
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4727
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4394
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4748
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 4988
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8092
ORA-06512: at line 1
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 562
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 5328
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 5381
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 7983
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8146
ORA-06512: at "SYS.DBMS_LOGMNR_INTERNAL", line 8302
ORA-06512: at "SYS.DBMS_LOGMNR_D", line 61
ORA-06512: at line 1
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
        ... 25 more```

**Comment by nekator** [comment]
Having `SUPPLEMENTAL_LOG_DATA_ALL` at database level leads to massive resource consumptions. So it would be greate to switch to `SUPPLEMENTAL_LOG_DATA_MIN` to redurce memory usage as a quick fix. 
It would be even better to only activate supplemental logging only on objects that should be monitored for changes. But i don´t know if this is possible without bigger changes.

**Comment by ant0nk** [comment]
> Having `SUPPLEMENTAL_LOG_DATA_ALL` at database level leads to massive resource consumptions. So it would be greate to switch to `SUPPLEMENTAL_LOG_DATA_MIN` to redurce memory usage as a quick fix.
> It would be even better to only activate supplemental logging only on objects that should be monitored for changes. But i don´t know if this is possible without bigger changes.

It is possible. That's what this PR is all about.

**Comment by Naros** [comment]
I'm closing this PR in favor of PR #238 which extends this PR will some additional checks & fixes a few test failures related to the changed enclosed within.

**Pull request closed without merging**
