### PR TITLE
DBZ-1064 Set default value only for non-nullable fields

### PR DESCRIPTION
**Pull request by jpechane**
Main issue - https://github.com/debezium/debezium/pull/723

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, this should still be updated to use the new base method where applicable.

**Comment by jpechane** [comment]
@gunnarmorling Yes, I waited for the main PR to be merged to make sure there is no need to rewirte

**Comment by gunnarmorling** [comment]
Makes sense! Just merged that one :)

**Comment by jpechane** [comment]
Requires https://github.com/debezium/debezium/pull/735 to pass failing test

**Comment by gunnarmorling** [comment]
Applied. Thanks, @jpechane!

**Pull request closed without merging**
