### PR TITLE
DBZ-2855 Make sure current redo log file is always selected

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-2855

This PR includes a modified version of the proposed fix by the reporter but still requires a test case.  I've reached out to find out if the reporter can clarify a more exact use case so that a test case can be built.  Until then, opening as a draft.

### CODE REVIEW

**Comment by mpermar** [comment]
Right. Replied in the JIRA ticket. I have the feeling this PR might not fix the actual cause.

**Comment by Naros** [comment]
@mpermar I went ahead and made your suggestion from the jira.  Lets see if this satisfies the problem.

**Comment by mpermar** [comment]
@Naros , proposing this alternative PR instead: https://github.com/debezium/debezium-incubator/pull/239

**Comment by gunnarmorling** [comment]
@Naros, could you check out @mpermar's alternative PR? Thx!

**Comment by Naros** [comment]
Closing this PR in favor of PR #239.

**Pull request closed without merging**
